language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t artur/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true artur/react-test npm test    

after_success: 
    - docker build -t arturkaluza3/multi-client ./client
    - docker build -t arturkaluza3/multi-server ./server
    - docker build -t arturkaluza3/multi-nginx ./nginx    
    - docker build -t arturkaluza3/multi-worker ./worker 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
    - docker push arturkaluza3/multi-client
    - docker push arturkaluza3/multi-server 
    - docker push arturkaluza3/multi-nginx 
    - docker push arturkaluza3/multi-worker 

